/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.List;
import javax.swing.JOptionPane;
import model.City;
import model.SystemAdmin;

/**
 *
 * @author shubham
 */
public class CreateCityPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateCityPanel
     */
    SystemAdmin sysAdmin;
    public CreateCityPanel(SystemAdmin sysAdmin) {
        initComponents();
        this.sysAdmin = sysAdmin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCityName = new javax.swing.JLabel();
        lblCityState = new javax.swing.JLabel();
        txtCityName = new javax.swing.JTextField();
        txtCityState = new javax.swing.JTextField();
        btnSaveCity = new javax.swing.JButton();

        setBackground(new java.awt.Color(43, 145, 191));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create City");

        lblCityName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCityName.setForeground(new java.awt.Color(255, 255, 255));
        lblCityName.setText("City Name");

        lblCityState.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCityState.setForeground(new java.awt.Color(255, 255, 255));
        lblCityState.setText("City State");

        btnSaveCity.setForeground(new java.awt.Color(43, 145, 191));
        btnSaveCity.setText("Save City");
        btnSaveCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCityName)
                            .addComponent(lblCityState))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCityName)
                            .addComponent(txtCityState, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnSaveCity)))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCityName)
                    .addComponent(txtCityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCityState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCityState))
                .addGap(36, 36, 36)
                .addComponent(btnSaveCity)
                .addContainerGap(435, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCityActionPerformed
        // TODO add your handling code here:
        List<City> cities = sysAdmin.getCities();
        City c = sysAdmin.addCity();
        String cid =  String.valueOf(cities.size() + Integer.parseInt("100"));
        String name = String.valueOf(txtCityName.getText());
        String state = String.valueOf(txtCityState.getText());
        if(name.length()==0 || state.length()==0){
            JOptionPane.showMessageDialog(this, "Enter All fields");
            return;
        }
        c.setId(cid);
        c.setState(state);
        c.setName(name);
        
        txtCityName.setText("");
        txtCityState.setText("");
        
        JOptionPane.showMessageDialog(this, "City Info Saved"); 
    }//GEN-LAST:event_btnSaveCityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveCity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCityName;
    private javax.swing.JLabel lblCityState;
    private javax.swing.JTextField txtCityName;
    private javax.swing.JTextField txtCityState;
    // End of variables declaration//GEN-END:variables
}
