/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.City;
import model.Community;
import model.House;
import model.SystemAdmin;

/**
 *
 * @author shubham
 */
public class ViewHousePanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewHousePanel
     */
    SystemAdmin sysAdmin;
    public ViewHousePanel(SystemAdmin sysAdmin) {
        initComponents();
        this.sysAdmin = sysAdmin;
        populateCommunities();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHouses = new javax.swing.JTable();
        btnViewHouse = new javax.swing.JButton();
        btnUpdateHouse = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtHousePinCode = new javax.swing.JTextField();
        jComboBoxHouseCommunity = new javax.swing.JComboBox<>();
        lblHouseCommunity = new javax.swing.JLabel();
        btnSaveHouse = new javax.swing.JButton();
        lblHouseStreetAddress = new javax.swing.JLabel();
        txtHouseStreetAddress = new javax.swing.JTextField();
        lblHouseId = new javax.swing.JLabel();
        txtHouseId = new javax.swing.JTextField();

        setBackground(new java.awt.Color(43, 145, 191));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("View Houses");

        tblHouses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "House Id", "Street Address", "Pin Code", "Community"
            }
        ));
        jScrollPane1.setViewportView(tblHouses);

        btnViewHouse.setForeground(new java.awt.Color(43, 145, 191));
        btnViewHouse.setText("View House");
        btnViewHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHouseActionPerformed(evt);
            }
        });

        btnUpdateHouse.setForeground(new java.awt.Color(43, 145, 191));
        btnUpdateHouse.setText("Update House");
        btnUpdateHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateHouseActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pin Code");

        lblHouseCommunity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHouseCommunity.setForeground(new java.awt.Color(255, 255, 255));
        lblHouseCommunity.setText("Community");

        btnSaveHouse.setForeground(new java.awt.Color(43, 145, 191));
        btnSaveHouse.setText("Save House");
        btnSaveHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveHouseActionPerformed(evt);
            }
        });

        lblHouseStreetAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHouseStreetAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblHouseStreetAddress.setText("Street Address");

        lblHouseId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHouseId.setForeground(new java.awt.Color(255, 255, 255));
        lblHouseId.setText("House Id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnViewHouse)
                            .addGap(36, 36, 36)
                            .addComponent(btnUpdateHouse))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(357, 357, 357)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHouseStreetAddress)
                                    .addComponent(lblHouseCommunity)
                                    .addComponent(lblHouseId))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHouseStreetAddress)
                                    .addComponent(txtHousePinCode)
                                    .addComponent(txtHouseId, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(jComboBoxHouseCommunity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(btnSaveHouse)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewHouse)
                    .addComponent(btnUpdateHouse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHouseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHouseId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHouseStreetAddress)
                    .addComponent(txtHouseStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHousePinCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxHouseCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHouseCommunity))
                .addGap(40, 40, 40)
                .addComponent(btnSaveHouse)
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveHouseActionPerformed
        // TODO add your handling code here:
        /*
        City c = (City)jComboBoxCities.getSelectedItem();
        if(txtCommunityName.getText().length()==0 || c==null){
            JOptionPane.showMessageDialog(this, "Enter All fields");
            return;
        }
        Community community = c.getCommunity(txtCommunityId.getText());
        if(txtCommunityName.getText().length()==0 || jComboBoxCities.getSelectedItem()==null){
            JOptionPane.showMessageDialog(this, "Enter All fields");
            return;
        }
        community.setCommunityId(String.valueOf(txtCommunityName.getText()));
        community.setCity((City)jComboBoxCities.getSelectedItem());
        
        JOptionPane.showMessageDialog(this, "Community Info Updated");
        
        txtCommunityId.setText("");
        txtCommunityName.setText("");
        jComboBoxCities.setSelectedItem(null);
        populateTable();
        */
        Community community = (Community)jComboBoxHouseCommunity.getSelectedItem();
        if(txtHouseStreetAddress.getText().length()==0 || txtHousePinCode.getText().length()==0 || community==null){
            JOptionPane.showMessageDialog(this, "Enter All fields");
            return;
        }
        House h = community.getHouse(txtHouseId.getText());
        h.setStreetAddress(String.valueOf(txtHouseStreetAddress.getText()));
        h.setPinCode(String.valueOf(txtHousePinCode.getText()));
        
        JOptionPane.showMessageDialog(this, "House Info Updated");
        
        txtHouseId.setText("");
        txtHouseStreetAddress.setText("");
        txtHousePinCode.setText("");
        jComboBoxHouseCommunity.setSelectedItem(null);
        populateTable();
        
        

    }//GEN-LAST:event_btnSaveHouseActionPerformed

    private void btnUpdateHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateHouseActionPerformed
        // TODO add your handling code here:
        int selectedrowIndex = tblHouses.getSelectedRow();
        if(selectedrowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select row to view the details");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblHouses.getModel();
        House h = (House) model.getValueAt(selectedrowIndex, 1);
        txtHouseId.setText(String.valueOf(h.getHouseId()));
        txtHouseId.setEditable(false);
        txtHouseStreetAddress.setText(String.valueOf(h.getStreetAddress()));
        txtHouseStreetAddress.setEditable(true);
        txtHousePinCode.setText(String.valueOf(h.getPinCode()));
        txtHousePinCode.setEditable(true);
        jComboBoxHouseCommunity.setSelectedItem(h.getCommunity());
        jComboBoxHouseCommunity.setEditable(false);
    }//GEN-LAST:event_btnUpdateHouseActionPerformed

    private void btnViewHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHouseActionPerformed
        // TODO add your handling code here:
        /*
        int selectedrowIndex = tblCommunities.getSelectedRow();
        if(selectedrowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select row to view the details");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblCommunities.getModel();
        Community c = (Community) model.getValueAt(selectedrowIndex, 1);
        txtCommunityId.setText(String.valueOf(c.getCommunityId()));
        txtCommunityId.setEditable(false);
        txtCommunityName.setText(String.valueOf(c.getCommunityName()));
        txtCommunityName.setEditable(false);
        jComboBoxCities.setSelectedItem(c.getCity());
        jComboBoxCities.setEditable(false);
        */
        int selectedrowIndex = tblHouses.getSelectedRow();
        if(selectedrowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select row to view the details");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblHouses.getModel();
        House h = (House) model.getValueAt(selectedrowIndex, 1);
        txtHouseId.setText(String.valueOf(h.getHouseId()));
        txtHouseId.setEditable(false);
        txtHouseStreetAddress.setText(String.valueOf(h.getStreetAddress()));
        txtHouseStreetAddress.setEditable(false);
        txtHousePinCode.setText(String.valueOf(h.getPinCode()));
        txtHousePinCode.setEditable(false);
        jComboBoxHouseCommunity.setSelectedItem(h.getCommunity());
        jComboBoxHouseCommunity.setEditable(false);
        
    }//GEN-LAST:event_btnViewHouseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveHouse;
    private javax.swing.JButton btnUpdateHouse;
    private javax.swing.JButton btnViewHouse;
    private javax.swing.JComboBox<Object> jComboBoxHouseCommunity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHouseCommunity;
    private javax.swing.JLabel lblHouseId;
    private javax.swing.JLabel lblHouseStreetAddress;
    private javax.swing.JTable tblHouses;
    private javax.swing.JTextField txtHouseId;
    private javax.swing.JTextField txtHousePinCode;
    private javax.swing.JTextField txtHouseStreetAddress;
    // End of variables declaration//GEN-END:variables

    private void populateCommunities() {
        List<City> cities = sysAdmin.getCities();
        jComboBoxHouseCommunity.removeAllItems();
        for(City c : cities){
            for(Community community : c.getCommunityList()){
                jComboBoxHouseCommunity.addItem(community);
            }
        }
    }

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblHouses.getModel();
        model.setRowCount(0);
        for(City c: sysAdmin.getCities()){
            for(Community community : c.getCommunityList()){
                for(House h : community.getHouseList()){
                    Object[] row = new Object[4];
                    row[0] = h.getHouseId();
                    row[1] = h;
                    row[2] = h.getPinCode();
                    row[3] = community;
                    model.addRow(row);
                }
            }
        }
    }
}
